#!/bin/sh
#
# This is a script suitable for use in a crontab.  It checks to make sure
# your bot is running.  YOU NEED A SEPARATE CRON JOB FOR EACH BOT.  If your
# bot isn't found, it'll try to start it back up.
#
# You'll need to edit this script for your bot.
#

# change this to the directory you run your bot from:
botdir="/home/paradox/EnergyMech/"

# change this to the name of your bot's script in that directory:
botscript="EnergyMech"

cd $botdir
if test -r EnergyMech.pid; then
  # there is a pid file -- is it current?
  botpid=`cat EnergyMech.pid`
  if `kill -CHLD $botpid >/dev/null 2>&1`; then
    # it's still going
    # back out quietly
    exit 0
  fi
  echo ""
  echo "Stale EnergyMech.pid file (erasing it)"
  rm -f EnergyMech.pid
fi
echo ""
echo "Couldn't find the bot running.  Reloading it..."
echo ""
$botscript
