Annihlation Rate = %0, maybe you should give me an oil change?
Annihlation Rate = %1
Annihlation Rate = %2
Annihlation Rate = %3
Annihlation Rate = %4
Annihlation Rate = %5
Annihlation Rate = %6
Annihlation Rate = %7
Annihlation Rate = %8
Annihlation Rate = %9
Annihlation Rate = %10
Annihlation Rate = %11
Annihlation Rate = %12
Annihlation Rate = %13
Annihlation Rate = %14
Annihlation Rate = %15
Annihlation Rate = %16
Annihlation Rate = %17
Annihlation Rate = %18
Annihlation Rate = %19
Annihlation Rate = %20
Annihlation Rate = %21
Annihlation Rate = %22
Annihlation Rate = %23
Annihlation Rate = %24
Annihlation Rate = %25
Annihlation Rate = %26
Annihlation Rate = %27
Annihlation Rate = %28
Annihlation Rate = %29
Annihlation Rate = %30
Annihlation Rate = %31
Annihlation Rate = %32
Annihlation Rate = %33
Annihlation Rate = %34
Annihlation Rate = %35
Annihlation Rate = %36
Annihlation Rate = %37
Annihlation Rate = %38
Annihlation Rate = %39
Annihlation Rate = %40
Annihlation Rate = %41
Annihlation Rate = %42
Annihlation Rate = %43
Annihlation Rate = %44
Annihlation Rate = %45
Annihlation Rate = %46
Annihlation Rate = %47
Annihlation Rate = %48
Annihlation Rate = %49
Annihlation Rate = %50
Annihlation Rate = %51
Annihlation Rate = %52
Annihlation Rate = %53
Annihlation Rate = %54
Annihlation Rate = %55
Annihlation Rate = %56
Annihlation Rate = %57
Annihlation Rate = %58
Annihlation Rate = %59
Annihlation Rate = %60
Annihlation Rate = %61
Annihlation Rate = %62
Annihlation Rate = %63
Annihlation Rate = %64
Annihlation Rate = %65
Annihlation Rate = %66
Annihlation Rate = %67
Annihlation Rate = %68
Annihlation Rate = %69 wish I was in the 69er!
Annihlation Rate = %70
Annihlation Rate = %71
Annihlation Rate = %72
Annihlation Rate = %73
Annihlation Rate = %74
Annihlation Rate = %75
Annihlation Rate = %76
Annihlation Rate = %77
Annihlation Rate = %78
Annihlation Rate = %79
Annihlation Rate = %80
Annihlation Rate = %81
Annihlation Rate = %82
Annihlation Rate = %83
Annihlation Rate = %84
Annihlation Rate = %85
Annihlation Rate = %86
Annihlation Rate = %87
Annihlation Rate = %88
Annihlation Rate = %89
Annihlation Rate = %90
Annihlation Rate = %91
Annihlation Rate = %92
Annihlation Rate = %93
Annihlation Rate = %94
Annihlation Rate = %95
Annihlation Rate = %96
Annihlation Rate = %97
Annihlation Rate = %98
Annihlation Rate = %99
Annihlation Rate = %100 Congradulations
Annihlation Rate = %101 sorry I nipped bit of your ear too
Annihlation Rate = %102 watch out mad bot on the loose
Annihlation Rate = %103 ohh I'm sorry I got 3% of your ass too
Annihlation Rate = %104 there goes part of the toilet
Annihlation Rate = %105 I ate an extra bowl of cereal today
Annihlation Rate = %106 watch out m4dc0w on the loose
Annihlation Rate = %107 looks like pooh got it in the ass
Annihlation Rate = %5000 sorry didn't mean to blow the universe up
