void	do_rules(char *from, char *to, char *rest);
void	do_addrule(char *from, char *to, char *rest);
void	do_poet(char *from, char *to, char *rest);
/*
void	do_show_values(char *from, char *to, char *rest);
*/
void	do_apoet(char *from, char *to, char *rest);
void	do_bulletin(char *from, char *to, char *rest);
void	do_away(char *from, char *to, char *rest);
void	do_reboot(char *from, char *to, char *rest);
void do_showidle(char *from, char *to, char *rest);
int toggle(char *from, int *bleah, char *what, ...);
int stats(char *from, int *bleah, char *what, ...);
void	do_status(char *from, char *to, char *rest);
void do_cool(char *from, char *to, char *rest);
void    do_ping(char *from, char *to, char *rest);
void    do_getch(char *from, char *to, char *rest);
void    do_cmdchar(char *from, char *to, char *rest);
void	do_userhost(char *from, char *to, char *rest);
void	do_logtog(char *from, char *to, char *rest);
void	do_shittog(char *from, char *to, char *rest);
void	do_aoptog(char *from, char *to, char *rest);
void	do_singtog(char *from, char *to, char *rest);
void	do_masstog(char *from, char *to, char *rest);
void	do_bonktog(char *from, char *to, char *rest);
void	do_greettog(char *from, char *to, char *rest);
void	do_prottog(char *from, char *to, char *rest);
void	do_pubtog(char *from, char *to, char *rest);
void	do_iktog(char *from, char *to, char *rest);
void	do_sotog(char *from, char *to, char *rest);
void	do_bktog(char *from, char *to, char *rest);
void	do_cktog(char *from, char *to, char *rest);
void	do_sdtog(char *from, char *to, char *rest);
void	do_walltog(char *from, char *to, char *rest);
void 	do_wall(char *from, char *to, char *rest);
void	sendmsg(char *to, char *rest);
void 	do_flip(char *from, char *to, char *rest);
void 	do_setmpl(char *from, char *to, char *rest);
void 	do_setfpl(char *from, char *to, char *rest);
void 	do_setncl(char *from, char *to, char *rest);
void 	do_setikt(char *from, char *to, char *rest);
void 	do_setmal(char *from, char *to, char *rest);
void 	do_limit(char *from, char *to, char *rest);
void 	do_chanstats(char *from, char *to, char *rest);
void 	do_stats(char *from, char *to, char *rest);
void 	do_credits(char *from, char *to, char *rest);
void	do_ctof(char *from, char *to, char *rest);
void 	do_ftoc(char *from, char *to, char *rest);
void	do_ktoc(char *from, char *to, char *rest);
void	do_ctok(char *from, char *to, char *rest);
void	do_dtoh(char *from, char *to, char *rest);

