char *my_stristr(char *s1, char *s2);
char *left(char *string, int i);
int matches(char *ma, char *na );
void showspymsg(char *person, char *msg);
time_t getthetime(void);
int percent_caps(char *string);
char *find_person( char *from, char *person );
char *nick2uh(char *from, char *userhost, int type);
char *format_uh(char *userhost, int type);
char *right(char *string, int num);
void no_chan(char *from);
void mode3(char *channel, char *mode, char *data);
void deop_ban(char *channel, char *nick, char *nuh);
void deop_siteban(char *channel, char *nick, char *nuh);
void deop_bannick(char *channel, char *nick);
void deop_sitebannick(char *channel, char *nick);
void deop_screwban(char *channel, char *nick);
void shit_action(char *who, char *channel);
void prot_action(char *from, char *channel, char *protnuh);
char *cluster(char *host);

