#include "config.h"
/* channel.c */
char *ConvertChanMode(char *StrModes, unsigned char Modes);
char *GetModeString(char *ModeString, int PlusModes, int MinModes, char *key, char *limit);
char *get_enforced_modes(char *name);
int set_enforced_modes(char *name, char *themodes);
int add_spy_chan(char *name, char *nick);
int del_spy_chan(char *name, char *nick);
void show_spy_list(char *from, char *name);
void send_spy_chan(char *name, char *text);
int is_spy_chan(char *name, char *nick);
void AddRegChan(char *name);
int join_channel(char *name, int join_mode);
int mychannel(char *name);
int leave_channel(char *name);
int mark_success(char *name);
int mark_failed(char *name);
void show_channellist(char *user);
void reset_channels(int Mode);
void setcurrentchannel(char *channel);
char *currentchannel(void);
int add_user_to_channel(char *channel, char *nick, char *user, char *host);
int remove_user_from_channel(char *channel, char *nick);
void show_chanusers(char *nick, char *channel);
void change_nick(char *oldnick, char *newnick);
void remove_user(char *nick);
void send_kickall(char *nick, char *msg);
void send_banall(char *nuh);
void send_screwbanall(char *nuh);
void update_idletime(char *channel, char *nuh);
void update_flood(char *channel, char *nuh);
int num_on_channel(char *channel, char *uh);
int tot_num_on_channel(char *channel);
void cycle_channel(char *channel);
void idle_kick(void);
int show_users_on_channel(char *from, char *channel);
void add_channelmode(char *channel, unsigned int mode, char *params);
void del_channelmode(char *channel, unsigned int mode, char *params);
void change_usermode(char *channel, char *user, unsigned int mode);
int open_channel(char *channel);
void channel_massop(char *channel, char *pattern);
void channel_massdeop(char *channel, char *pattern);
void channel_masskick(char *channel, char *pattern);
void channel_masskickban(char *channel, char *pattern);
int invite_to_channel(char *user, char *channel);
char *username(char *nick);
unsigned int usermode(char *channel, char *nick);
void channel_massunban(char *channel);
void channel_unban(char *channel, char *user);
CHAN_list *search_chan(char *name);
void add_ban(BAN_list **b_list, char *banstring);
void clear_all_bans(BAN_list **b_list);
int delete_ban(BAN_list **b_list, char *banstring);
void SaveDatFile(CHAN_list *ChanPtr);
