/* function.c */
char *GetLevelName(int level);
int ConvertAOp(char *s);
int ConvertProt(char *s);
int ConvertLevel(char *s);
int exist(char *filename);
char *left(char *string, int i);
void shitkick(char *who, char *channel);
void showspymsg(char *person, char *msg);
void make_process(char *name, char *args);
void massprot_action(char *from, char *channel, char *buffer);
void prot_action(char *from, char *protnuh, char *channel);
void takeop(char *channel, char *nicks);
void giveop(char *channel, char *nicks);
void sep_userhost(char *uhost, char *nick, char *user, char *host, char *machine);
void ban_user(char *channel, char *who);
void site_ban(char *channel, char *who);
void screw_ban(char *channel, char *who, int num);
void signoff(char *from, char *reason);
void mode3(char *channel, char *mode, char *data);
void alt_ques(char *string);
char *rand_ques(char *string, int num);
void rand_quesfunc(char *string);
char *fix_channel(char *channel);
char *find_channel(char *to, char **rest);
char *getuserhost2(char *nick);
char *find_person(char *from, char *nick);
void steal_channels(void);
int numchar(char *string, char c);
char *right(char *string, int num);
char *cluster(char *userhost);
char *cluster_busted(char *userhost);
char *cluster_orig(char *userhost);
void bot_reply(char *to, int num);
