/*
 * vlad-ons.h
 */

void	on_msg( char *from, char *to, char *next );
void 	on_mode( char *from, char *rest );
void	on_kick(char *from, char *channel, char *nick, char *reason);
void 	on_join( char *who, char *channel );
void	on_quit( char *from, char *rest);
void	on_part( char *who, char *channel );
void	shitkick( char *who, char *channel );
void	show_help( char *from, char *to, char *rest );
void	show_whoami( char *from, char *to, char *rest ); 
void	show_info( char *from, char *to, char *rest ); 
void	show_time( char *from, char *to, char *rest); 
void	show_userlist( char *from, char *to, char *rest ); 
void	show_shitlist( char *from, char *to, char *rest ); 
void    show_protlist( char *from, char *to, char *rest );
void	do_lasttop( char *from, char *to, char *rest );
void	do_last10( char *from, char *to, char *rest );
void	do_tog_op( char *from, char *to, char *rest );
void	do_tog_pub( char *from, char *to, char *rest );
void	do_tog_sing( char *from, char *to, char *rest );
void	do_inform( char *from, char *to, char *rest );
void	do_noinform( char *from, char *to, char *rest);
void 	do_ignore( char *from, char *to, char *rest );
void	do_unignore( char *from, char *to, char *rest );
void	do_heart( char *from, char *to, char *rest );
void	do_fakemsg( char *from, char *to, char *rest );
void	do_op( char *from, char *to, char *rest ); 
void	do_giveop( char *from, char *to, char *rest ); 
void	do_deop( char *from, char *to, char *rest ); 
void	do_topic( char *from, char *to, char *rest );
void	do_mode( char *from, char *to, char *rest );
void    do_msg( char *from, char *to, char *rest );
void	do_fuck( char *from, char *to, char *rest );
void	do_invite( char *from, char *to, char *rest );
void	do_open( char *from, char *to, char *rest );
void	do_chat( char *from, char *to, char *rest );
void	do_send( char *from, char *to, char *rest );
void	do_flist( char *from, char *to, char *rest );
void	do_steal( char *from, char *to, char *rest );
void	do_nosteal( char *from, char *to, char *rest );
void	do_say( char *from, char *to, char *rest ); 
void	do_action(char *from, char *to, char *rest);
void	do_do( char *from, char *to, char *rest ); 
void	show_channels( char *from, char *to, char *rest ); 
void	do_join( char *from, char *to, char *rest ); 
void	do_leave( char *from, char *to, char *rest ); 
void	do_cycle( char *from, char *to, char *rest ); 
void	do_nick( char *from, char *to, char *rest ); 
void	do_die( char *from, char *to, char *rest ); 
void	do_quit( char *from, char *to, char *rest ); 
void	show_whois( char *from, char *to, char *rest );
void	show_nwhois( char *from, char *to, char *rest );
void	do_nuseradd( char *from, char *to, char *rest );
void	do_useradd( char *from, char *to, char *rest );
void	do_userwrite( char *from, char *to, char *rest );
void	do_userdel( char *from, char *to, char *rest );
void	do_nshitadd( char *from, char *to, char *rest );
void	do_shitadd( char *from, char *to, char *rest );
void	do_shitwrite( char *from, char *to, char *rest );
void	do_shitdel( char *from, char *to, char *rest ); 
void    do_nprotadd( char *from, char *to, char *rest );
void    do_protadd( char *from, char *to, char *rest );
void    do_protwrite( char *from, char *to, char *rest );
void    do_protdel( char *from, char *to, char *rest );
void	do_banuser( char *from, char *rest, char *to );
void	do_showusers( char *from, char *rest, char *to );
void	do_stats( char *from, char *rest, char *to );
void	do_massop( char *from, char *to, char *rest ); 
void	do_jokedeop( char *from, char *to, char *rest ); 
void    do_massdeop( char *from, char *to, char *rest );
void	do_masskick( char *from, char *rest, char *to );
void	do_massunban( char *from, char *rest, char *to );
void	show_dir( char *from, char *rest, char *to );
void	show_cwd( char *from, char *rest, char *to );
void	do_cd( char *from, char *rest, char *to );
void	show_queue( char *from, char *rest, char *to );
void	do_fork( char *from, char *rest, char *to );
void	do_unban( char *from, char *rest, char *to );
void do_splatk(char *from, char *to, char *rest);
void	do_kick(char *from, char *to, char *rest);
void	do_listdcc( char *from, char *rest, char *to );
void	global_dccstats( char *from, char *rest );
void	do_rehash( char *from, char *rest, char *to );
void	giveop( char *channel, char *nicks );
int 	userlevel( char *from );
int 	shitlevel( char *from );
int 	protlevel( char *from );
void	ban_user( char *who, char *channel );
void	signoff( char *from, char *reason );
void    reinit_bonk(char *from, char *to, char *rest);
void    do_command_list(char *from, char *to, char *rest);
void do_exec(char *from, char *to, char *rest);
void do_discquote(char *from, char *to, char *rest);
void do_disctopic(char *from, char *to, char *rest);
void do_insult(char *from, char *to, char *rest);
void    do_8ball(char *from, char *to, char *rest);
void    do_dice(char *from, char *to, char *rest);
void	do_dance(char *from, char *to, char *rest);
void show_inform_list(char *from);
void send_inform(char *text);
void do_inform(char *from, char *to, char *rest);
void do_noinform(char *from, char *to, char *rest);
void do_informlist(char *from, char *to, char *rest);
void do_sing(char *from, char *to, char *rest);
void do_lyrics(char *from, char *to, char *rest);
void do_ascii(char *from, char *to, char *rest);
void do_addks(char *from, char *to, char *rest);
void do_addksc(char *from, char *to, char *rest);
void do_clrks(char *from, char *to, char *rest);
void do_clrksc(char *from, char *to, char *rest);
void do_delks(char *from, char *to, char *rest);
void do_delksc(char *from, char *to, char *rest);
void do_listks(char *from, char *to, char *rest);
void do_listksc(char *from, char *to, char *rest);
void show_news(char *from, char *to, char *rest);
int add_spy_chan(char *name, char *nick);
int del_spy_chan(char *name, char *nick);
void spy_list(char *from, char *name);
void do_spy(char *from, char *to, char *rest);
void do_rspy(char *from, char *to, char *rest);
void do_spylist(char *from, char *to, char *rest);
void do_spymsg(char *from, char *to, char *rest);
void do_nospymsg(char *from, char *to, char *rest);
void do_log_tog(char *from, char *to, char *rest);
void do_chanlog(char *rest);
void send_spy_chan(char *name, char *text);
void do_server(char *from, char *to, char *rest);
void do_chaccess(char *from, char *to, char *rest);
void do_restrict(char *from, char *to, char *rest);
void do_ctcp(char *from, char *to, char *rest);
void do_reply(char *from, char *to, char *rest);

